### ISSUE TITLE
Configure Default Slide Styles in the App

### ISSUE THREAD

**Issue by LucitheR** [abbr/ShowPreper#14]
Hi,
i'm using ShowPreper for inhouse training.
it would be nice to have a Documentation where to configure the default styles to met certain CI-Standards.
i found the default_palettes.json but a new item there does not show in the Styler. 

Any Pointers?

**Comment by abbr** [comment]
The initial slide styles of a new presentation is hard-coded in file `src/sources/default.spj.js`. ShowPreper interprets the term *Default Slide Styles* (or *Styles for Default Slides*) as styles of slides without customization, which can be set in editor.
